# -*- coding: utf-8 -*-
"""Exhibit 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5_aCpGANcuqoDFv-_YMs6s5COYQ1YpO
"""

# Import linear regression models
import pandas as pd
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV

# Load all the data
df_2022 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRJTa-3SWvjM7Guv9Kd3UnDIlHvoOXl1yBsVjxI2COqBvHyUrvmUfLy7FR29TlbCw/pub?gid=129332240&single=true&output=csv')
df_2023 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRJTa-3SWvjM7Guv9Kd3UnDIlHvoOXl1yBsVjxI2COqBvHyUrvmUfLy7FR29TlbCw/pub?gid=840602606&single=true&output=csv')
df_2023.head()  # Visualize small portion of the data

# Split the data into training and testing sets
df_train = df_2022
df_test = df_2023

# Define features to remove from the feature data (i.e., X)
drop_for_X = ['Date','Close','Adj Close']

# Partition the training data into features and target
X_train = df_train.drop(columns=drop_for_X)
y_train = df_train.Close
# Fit the model
linreg = LinearRegression()
linreg.fit(X_train, y_train)

# Partition the testing data into features and target
X_test = df_test.drop(columns=drop_for_X)
y_test = df_test.Close

# Predict the closing prices
y_test_predictions = pd.DataFrame(linreg.predict(X_test))

print(f'Y test predictions: {y_test_predictions}')

train_score = linreg.score(X_train, y_train)
test_score = linreg.score(X_test, y_test)

print(f'The train score is {train_score:.3f} and the test score is {test_score:.3f}')
y_test_predictions

# Split the data into training and testing sets
df_train = df_2022
df_test = df_2023

# Define features to remove from the feature data (i.e., X)
drop_for_X = ['Date','Close', 'Adj Close', 'High', 'Low']

# Partition the training data into features and target
X_train = df_train.drop(columns=drop_for_X)
y_train = df_train.Close
# Fit the model
linreg = LinearRegression()
linreg.fit(X_train, y_train)

# Partition the testing data into features and target
X_test = df_test.drop(columns=drop_for_X)
y_test = df_test.Close

# Predict the closing prices
y_test_predictions = pd.DataFrame(linreg.predict(X_test))

print(f'Y test predictions: {y_test_predictions}')

train_score = linreg.score(X_train, y_train)
test_score = linreg.score(X_test, y_test)

print(f'The train score is {train_score:.3f} and the test score is {test_score:.3f}')
y_test_predictions

# Load all the data
df_2022 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRJTa-3SWvjM7Guv9Kd3UnDIlHvoOXl1yBsVjxI2COqBvHyUrvmUfLy7FR29TlbCw/pub?gid=1079320371&single=true&output=csv')
df_2023 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vRJTa-3SWvjM7Guv9Kd3UnDIlHvoOXl1yBsVjxI2COqBvHyUrvmUfLy7FR29TlbCw/pub?gid=465026525&single=true&output=csv')
df_2023.head()  # Visualize small portion of the data

# Split the data into training and testing sets
df_train = df_2022
df_test = df_2023

# Define features to remove from the feature data (i.e., X)
drop_for_X = ['Date','Close', 'Adj Close', 'Low', 'High']

# Partition the training data into features and target
X_train = df_train.drop(columns=drop_for_X)
y_train = df_train.Close
# Fit the model
linreg = LinearRegression()
linreg.fit(X_train, y_train)

# Partition the testing data into features and target
X_test = df_test.drop(columns=drop_for_X)
y_test = df_test.Close

# Predict the closing prices
y_test_predictions = pd.DataFrame(linreg.predict(X_test))

print(f'Y test predictions: {y_test_predictions}')

train_score = linreg.score(X_train, y_train)
test_score = linreg.score(X_test, y_test)

print(f'The train score is {train_score:.3f} and the test score is {test_score:.3f}')
y_test_predictions